### ISSUE TITLE
I can not install this app

### ISSUE THREAD

**Issue by abdullah-abunada** [SumitMunot/fedena-upgradation#5]
Hi Everybody,

I can't install this app, because while installation some errors are raised in iconv gem.
I'm use Ruby 2.2 64X .

Best,

**Comment by SumitMunot** [comment]
Can you please post error here in details @abdullah-abunada

**Comment by abdullah-abunada** [comment]
Hi @SumitMunot
I installed the project successfully, and now I want to continue development on this project. 
So, Can you tell me if all functionality are running will or not, and list all bugs at this version please?
The first issue I faced it,
1- I can't login because I did't have the username and password,
2- The system is very slow during running.
Please help me on that.

Best

**Comment by sanket-redkar** [comment]
Please check rake file there is one rake *`rake db:create_users` *to create
users.

**Comment by abdullah-abunada** [comment]
Thank you, I solved it, but I notice some bugs in users controller like change password,
and there are other problem in student model, the system could not load it form time to time.

**Comment by SumitMunot** [comment]
Yes working on that issue.. will solve that soon.. @abdullah-abunada
